### ISSUE TITLE
F-Prefix Syntax Errors

### ISSUE THREAD

**Issue by andyhernandez** [clemfromspace/scrapy-selenium#15]
I'm getting syntax errors lines 30, 32, 35, 44.    

Here is the output:
`>>> from scrapy_selenium import SeleniumRequest
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scrapy_selenium/__init__.py", line 2, in <module>
    from .middlewares import SeleniumMiddleware
  File "/usr/local/lib/python2.7/site-packages/scrapy_selenium/middlewares.py", line 30
    webdriver_base_path = f'selenium.webdriver.{driver_name}'`

When running through some linters I get that the issue seems to be coming from the f-prefix that was was introduced in Python 3.  I'm getting this error on Python 2.7.

**Comment by andyhernandez** [comment]
I just went through some testing and noticed that this package is only compatible with Python 3.  I've adjusted my code accordingly.  Can you add a note to the main package docs noting compatibility? 

Either way, thanks for the the package. It is awesome!
