### ISSUE TITLE
Middleware throws error during crawl start

### ISSUE THREAD

**Issue by hubbubca** [clemfromspace/scrapy-selenium#27]
I'm sure I'm doing something wrong, as soon as I add the middleware it all breaks

```
DOWNLOADER_MIDDLEWARES = {
    'strainscraper.middlewares.StrainscraperDownloaderMiddleware': 543,
}
```
scrapy works fine

but
```
DOWNLOADER_MIDDLEWARES = {
    'scrapy_selenium.SeleniumMiddleware': 800
}
```
and
```
DOWNLOADER_MIDDLEWARES = {
    'strainscraper.middlewares.StrainscraperDownloaderMiddleware': 543,
}

```

causes the following

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/downloader/__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 71, in from_crawler
    browser_executable_path=browser_executable_path
  File "/usr/local/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 43, in __init__
    for argument in driver_arguments:
builtins.TypeError: 'NoneType' object is not iterable

2019-01-11 12:55:33 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/downloader/__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 71, in from_crawler
    browser_executable_path=browser_executable_path
  File "/usr/local/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 43, in __init__
    for argument in driver_arguments:
TypeError: 'NoneType' object is not iterable

```

As I say,  I'm doubtlessly doing something wrong, any help would be appreciated :)

Cheers,
PJ

**Comment by clemfromspace** [comment]
Hey @hubbubca ,

Did you have `SELENIUM_DRIVER_ARGUMENTS=['-headless']` in your settings?
I guess your error is showing up because of the `SELENIUM_DRIVER_ARGUMENTS` being `None` (and so `driver_arguments` is `None` too and not iterable).

I guess I should anyway make a default fallback when the `SELENIUM_DRIVER_ARGUMENTS` is not provided anyway. But in the meantime, adding `SELENIUM_DRIVER_ARGUMENTS=['-headless']` (or an empty array btw should solve your issue).

**Comment by hubbubca** [comment]
You guessed right :).
