### ISSUE TITLE
Geckodriver v0.25.0: "Unable to find a matching set of capabilities"

### ISSUE THREAD

**Issue by niccolomineo** [clemfromspace/scrapy-selenium#48]
````
2019-09-11 13:26:31 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:58175/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:firefoxOptions": {"args": ["-headless"]}}}, "desiredCapabilities": {"browserName": "firefox", "acceptInsecureCerts": true, "marionette": true, "moz:firefoxOptions": {"args": ["-headless"]}}}
2019-09-11 13:26:31 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): 127.0.0.1:58175
2019-09-11 13:26:31 [urllib3.connectionpool] DEBUG: http://127.0.0.1:58175 "POST /session HTTP/1.1" 500 115
2019-09-11 13:26:31 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
Unhandled error in Deferred:
2019-09-11 13:26:31 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 184, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 188, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/core/downloader/__init__.py", line 86, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/utils/misc.py", line 142, in create_instance
    return objcls.from_crawler(crawler, *args, **kwargs)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 71, in from_crawler
    browser_executable_path=browser_executable_path
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__
    self.driver = driver_klass(**driver_kwargs)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


2019-09-11 13:26:31 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/core/downloader/__init__.py", line 86, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy/utils/misc.py", line 142, in create_instance
    return objcls.from_crawler(crawler, *args, **kwargs)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 71, in from_crawler
    browser_executable_path=browser_executable_path
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__
    self.driver = driver_klass(**driver_kwargs)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/nicco/.virtualenvs/myscraper/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by clemfromspace** [comment]
Looks like this error come from selenium: https://github.com/SeleniumHQ/selenium/issues/3884
