### ISSUE TITLE
Package fails to install with pip 20.x

### ISSUE THREAD

**Issue by alxnik** [clemfromspace/scrapy-selenium#71]
Tried to install directly from git via pip as follows:
`-e git://github.com/clemfromspace/scrapy-selenium.git@master#egg=scrapy-selenium"`

which fails with pip 20.2 as in the below trace. pip 18.x works fine

```
Traceback (most recent call last):
        from pip.download import PipSession
    ModuleNotFoundError: No module named 'pip.download'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "[redacted]\.env\src\scrapy-selenium\setup.py", line 10, in <module>
    ModuleNotFoundError: No module named 'pip._internal.download'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by miettal** [comment]
I also encountered the same problem.

**Comment by tristanlatr** [comment]
Is there a workaround for this issue ?
The best practice would be to have a static list of requirements, what's the need of the using pip internals ?

We can read in the [pip documentation](https://pip.pypa.io/en/stable/development/architecture/) : 
"Direct use of pip’s internals is not supported, and these internals can change at any time"
