### ISSUE TITLE
Got one error after changing to scrapy selenium

### ISSUE THREAD

**Issue by 1558204459** [clemfromspace/scrapy-selenium#9]
```
Traceback (most recent call last):
  File "E:\Users\lenovo\Anaconda3\envs\crawler\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "E:\Users\lenovo\Anaconda3\envs\crawler\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "E:\Users\lenovo\Anaconda3\envs\crawler\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "E:\Users\lenovo\Anaconda3\envs\crawler\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "E:\Users\lenovo\Anaconda3\envs\crawler\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\lenovo\Desktop\shunqi\shunqi\spiders\shunqiwang.py", line 59, in parse
    yield SeleniumRequest(self.base_urlt.format(i),self.contact_parse)
  File "E:\Users\lenovo\Anaconda3\envs\crawler\lib\site-packages\scrapy_selenium\http.py", line 29, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'url'
```

**Comment by 1558204459** [comment]
Everything configured right as your readme state
Change it to scrapy.Request(),everything become right
Didn't find which proceure get wrong

**Comment by 1558204459** [comment]
I am using windows operating system
